export const GAME_CONFIG = {
  WIDTH: 480,
  HEIGHT: 800,
  GRAVITY: 1000,
  MOVE_SPEED: 280,
  JUMP_FORCE: 750,
  MARGIN_X: 30,
  
  PLAYER: {
    WIDTH: 48,
    HEIGHT: 48,
    BOUNCE: 0.1,
    START_Y_RATIO: 0.8,
  },
  
  PLATFORM: {
    WIDTH: 90,
    HEIGHT: 18,
    MOVING_RANGE: { MIN: 80, MAX: 140 },
    MOVING_SPEED: { MIN: 50, MAX: 90 },
    BREAK_DELAY: 250,
  },
  
  COLLECTIBLE: {
    CARROT_SIZE: 28,
    CARROT_OFFSET_Y: 45,
    SPAWN_CHANCE: 0.35,
  },
  
  SCORING: {
    HEIGHT_FACTOR: 0.5,
    CARROT_POINTS: 50,
    BEST_SCORE_KEY: 'bunnyJumperBestScore',
  },
  
  DIFFICULTY: {
    EASY: {
      HEIGHT_THRESHOLD: 1500,
      GAP_Y: { MIN: 70, MAX: 110 },
      PLATFORM_DISTRIBUTION: { STATIC: 0.85, MOVING: 0.15, BREAKABLE: 0 },
    },
    MEDIUM: {
      HEIGHT_THRESHOLD: 3500,
      GAP_Y: { MIN: 85, MAX: 125 },
      PLATFORM_DISTRIBUTION: { STATIC: 0.65, MOVING: 0.25, BREAKABLE: 0.1 },
    },
    HARD: {
      HEIGHT_THRESHOLD: Infinity,
      GAP_Y: { MIN: 95, MAX: 135 },
      PLATFORM_DISTRIBUTION: { STATIC: 0.5, MOVING: 0.35, BREAKABLE: 0.15 },
    },
  },
  
  INITIAL_PLATFORMS: 18,
} as const
